# -*- coding: utf-8 -*-
# Author: Nianze A. Tao (Omozawa Sueno)
"""
Example config files generated by CLI should match the files in example folder.
"""
import os
import shutil
import tomllib
import subprocess
from pathlib import Path
import pytest


cwd = Path(__file__).parent
example_path = cwd.parent / "example/cli"


def test():
    subprocess.run("madmol -S", shell=True, check=True, cwd=cwd)
    with open(cwd / "config.toml", "rb") as f:
        config = tomllib.load(f)
    with open(example_path / "config.toml", "rb") as f:
        config_ = tomllib.load(f)
    assert config.keys() == config_.keys()
    for k, v in config.items():
        if isinstance(v, dict):
            assert v.keys() == config_[k].keys()
    with open(cwd / "model_config.toml", "rb") as f:
        model_config = tomllib.load(f)
    with open(example_path / "model_config.toml", "rb") as f:
        model_config_ = tomllib.load(f)
    assert model_config.items() == model_config_.items()

    # ------- try the example config -------
    with open(cwd / "config.toml", "r", encoding="utf-8") as f:
        _config = f.read()
    _config = _config.replace(
        'checkpoint_save_path = "/home/user/project/ckpt"',
        'checkpoint_save_path = "./project/ckpt"',
    )
    with open(cwd / "config.toml", "w", encoding="utf-8") as f:
        f.write(_config)
    with pytest.raises(subprocess.CalledProcessError):
        subprocess.run("madmol", shell=True, check=True, cwd=cwd)
    os.remove(cwd / "config.toml")
    os.remove(cwd / "model_config.toml")
    shutil.rmtree(cwd / "project")
